ALTER TABLE PERSONNE_ADRESSE DROP FOREIGN KEY FK_PERSONNE_ADRESSE_adresses_RUE
ALTER TABLE PERSONNE_ADRESSE DROP FOREIGN KEY FK_PERSONNE_ADRESSE_Personne_NUM
DROP TABLE PERSONNE
DROP TABLE ADRESSE
DROP TABLE PERSONNE_ADRESSE
